version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "2000:2000"
    volumes:
      - ./src:/src
    command: >
      sh -c  "flask db upgrade && flask run -h '0.0.0.0' -p 2000"
