"""empty message

Revision ID: 172224782914
Revises: 
Create Date: 2019-12-14 15:52:27.736632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172224782914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('Revoked_token')
    # ### end Alembic commands ###
